#!/bin/bash

ver="v0.0.1"

# build docker image
docker build . -t "mega-head:$ver"

# load image to minikube
minikube image load "mega-head:$ver"

# apply the change, if the pod template is updated, this triggers a rollout
kubectl apply -f deployment.yaml
