kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  type: "ExternalName"
  externalName: "dummy.com"

---

kind: Service
apiVersion: v1
metadata:
  name: consul
spec:
  type: "ExternalName"
  externalName: "dummy.com"

---

kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  type: "ExternalName"
  externalName: "dummy.com"

---

kind: Service
apiVersion: v1
metadata:
  name: mq
spec:
  type: "ExternalName"
  externalName: "dummy.com"