apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empty-mind
  name: empty-mind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empty-mind
  template:
    metadata:
      labels:
        app: empty-mind
    spec:
      containers:
      - image: docker.io/library/empty-mind:latest
        name: empty-mind
        imagePullPolicy: Never
        volumeMounts:
        - name: mymyconf
          mountPath: /etc/data
        - name: empty-mind-conf
          mountPath: /etc/conf
      volumes:
      - name: mymyconf
        configMap:
          name: myconf
      - name: empty-mind-conf
        configMap:
          name: empty-mind-conf
