apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    name: mypv
spec:
  capacity: 
    storage: 10Mi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  local:
    path: /root/kube-demo/vol
  nodeAffinity:
    required: 
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2
